name: Log Step
description: Demonstrate how to use reusable steps in a workflow

runs:
  using: 'composite'
  steps:
    - name: Step Name1
      id: process-step
      shell: bash 
      run: |
        echo "Log step - V3"
    - name: Step Name2
      shell: bash 
      run: |
        echo "Log Step: $(hostname)"